### ISSUE TITLE
wrap sed by dll

### ISSUE THREAD

**Issue by lbubos** [mbuilov/sed-windows#15]
Hello Michael,

do you plan to wrap functionality of sed.exe by native or .NET managed DLL?
I have a very old wrapper DLL in use, without sourcecode etc, from the 90's and I have to replace it by a newer implementation, if possible.

I'm usually using VS2019 ot VS2022, if important.

Thx a lot!

lbubos

**Comment by mbuilov** [comment]
Hello.

By wrapper dll, you mean a dll that internally calls sed.exe ?

I think it's possible to make a universal .dll that will run any .exe, but how would calling a function from a .dll be better than directly using the CreateProcess() API?

**Comment by lbubos** [comment]
Hello Michael, 

thx!

I don't mean a wrapper wich calls an (arbitrary) exe, but convert the exe into a Windows dll:
DllMain instead of main....

At the moment the exisiting dll is called in a NET Framework 4 application like this:

        [DllImport(SedDllName)]
        [return: MarshalAs(UnmanagedType.AnsiBStr)]
        public static extern string sed(string input, string pattern);

This call should be replaced by a new implementation.
The dll is very heavily used, so start of an external process/exe is the "last" option, if we really have no other possibilities.

I'm not sure if important: apart from replacement we have to port our NET Framework app to NET 6 or 8, and maybe medium/long term to .NET on linux.

I maybe can try myself, but I have very little experience in C/C++ (worked last time in the late 90s short time in C/C++).

I could compile the exe according your intructions (great work, by the way!!!)

lbubos

**Comment by mbuilov** [comment]
Hello.

I guess it's not that easy to convert sed.exe into a dll.

What are the difficulties in this:

1) License. GPLv3 doesn't seem to allow this to be done.

2) Technical: Sed is a streaming editor, so the dll API should probably be in the form
of "int sed(string script, stream input, stream output)"

3) An interpreted Sed script allows to open files and call other programs. Probably the layer using the Sed dll API should be given the ability to intercept these actions...

4) Initialization, finalization, error handling. Now the sed.exe code is written in such a way that it assumes only one-time initialization at the start of sed.exe; perhaps finalization (releasing resources) is not done completely, because ending the program releases resources automatically. Due to an error in the script, sed.exe simply exits the program... - error handing should be havily rewritten.

In my opinion it would take quite a bit of work to turn sed.exe into sed.dll, although it is certainly possible (by rewriting quite a lot of code), I haven't dived that deep into the code - only to fix minor bugs...

**Comment by lbubos** [comment]
thanks!
